server:
  port: 9092


Spring:
  application:
    name: Rating-service
  datasource:
    url: jdbc:mysql://localhost:3306/rating?createDatabaseIfNotExist=true

  config:
    import:
      - configserver:http://localhost:9094

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

